[theme]
primaryColor = "#7D2230"
backgroundColor = "#F6F3EB"
secondaryBackgroundColor = "#DED2BE"
textColor = "#23211E"
font = "Cormorant Garamond"

[server]
headless = true

[browser]
gatherUsageStats = false
